"""add profile and location fields

Revision ID: 0fdb13073d58
Revises: 7bd896a84b36
Create Date: 2026-06-23 22:06:13.149542

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fdb13073d58'
down_revision: Union[str, None] = '7bd896a84b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('location_text', sa.String(length=255), nullable=True))
    op.alter_column('transactions', 'receipt_base64',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transactions', 'receipt_mime_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('users', sa.Column('avatar_base64', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_mime_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_mime_type')
    op.drop_column('users', 'avatar_base64')
    op.alter_column('transactions', 'receipt_mime_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('transactions', 'receipt_base64',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('transactions', 'location_text')
    op.drop_column('transactions', 'longitude')
    op.drop_column('transactions', 'latitude')
    # ### end Alembic commands ###
