"""add totp two-factor auth columns

Revision ID: dd6d2dc2dc38
Revises: 219ff340232d
Create Date: 2026-08-02 17:50:17.528293

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6d2dc2dc38'
down_revision: Union[str, None] = '219ff340232d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('totp_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('totp_backup_codes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('mfa_challenge_token', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('mfa_challenge_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('mfa_attempts', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_users_mfa_challenge_token'), 'users', ['mfa_challenge_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mfa_challenge_token'), table_name='users')
    op.drop_column('users', 'mfa_attempts')
    op.drop_column('users', 'mfa_challenge_expires')
    op.drop_column('users', 'mfa_challenge_token')
    op.drop_column('users', 'totp_backup_codes')
    op.drop_column('users', 'totp_confirmed_at')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
